name: learn-github-actions-docker
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  hello-docker-job:
    runs-on: ubuntu-latest
      permissions:
        id-token: write # This is required for requesting the JWT
      steps:
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: arn:aws:iam::605836753444:role/DynamoDbGithubAccess
            aws-region: us-east-1
        - run: docker pull amazon/dynamodb-local:latest
        - run: docker image ls
        - run: docker run -d -p8000:8000 amazon/dynamodb-local:latest
        - run: sleep 1
        - run: aws dynamodb --endpoint "http://localhost:8000" list-tables