name: learn-github-actions-docker
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  hello-docker-job:
    runs-on: ubuntu-latest
    container: amazon/dynamodb-local:latest
    steps:
      - run: docker ps -a
      - run: docker container ls -a
      - run: aws dynamodb list-tables