name: learn-github-actions-docker
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  hello-docker-job:
    runs-on: ubuntu-latest
    steps:
      - run: ls -lah
      - run: aws help
      - run: docker